version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true

  mysql:
    container_name: taegong_mysql
    image: mysql:8.0-oracle
    volumes:
      - mysql_data_dev:/mysql
    env_file:
      - ./.env
    networks:
      - mynet
    ports:
      - 3306:3306

  backend:
    container_name: taegong_backend
    build: ./backend
    environment:
      MYSQL_HOST: "1234"
    entrypoint: /bin/bash
    command: -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --reload && alembic upgrade head"
    ports:
      - 8000:8000
    networks:
      - mynet
    # 작업이 끝나도 종료되지 않게 하는 명령
    tty: true
    depends_on:
      - mysql

volumes:
  mysql_data_dev: null

networks:
  mynet:
    driver: bridge