version: "3"

services:
  ## TODO 기본 틀만 잡았으며 추후에 수정 예정
  # ai:
  #   container_name: ai
  #   build:
  #     context: ./ai
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    tty: true

  mysql:
    container_name: taegong_mysql
    #    image: mysql:8.0-oracle
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mysql_data_dev:/mysql
    #    env_file:
    #      - ./.env
    networks:
      - mynet
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    container_name: taegong_backend
    build: ./backend
    entrypoint: /bin/bash
    command: -c "uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    networks:
      - mynet
    # 작업이 끝나도 종료되지 않게 하는 명령
    tty: true
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data_dev: null

networks:
  mynet:
    driver: bridge
