global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/xxxxxx'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true