#Create MySQL Image for JSP Tutorial Application
FROM mysql:8.0-oracle

WORKDIR /db

# Use the environment variables from the .env file
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=taegong
ENV MYSQL_USER=taegong
ENV MYSQL_PASSWORD=taegong

EXPOSE 3306

