## TODO 기본 틀만 잡았으며 추후에 수정 예정

# FROM python:3.10-slim

# ENV PYTHONUNBUFFERED 1
# ENV PYTHONDONTWRITEBYTECODE 1

# WORKDIR /ai
# COPY requirements.txt /ai
# RUN apt-get update \
#   # dependencies for building Python packages
#   && apt-get install -y build-essential \
#   # psycopg2 dependencies
#   && apt-get install -y libpq-dev
# RUN pip install --upgrade pip
# RUN pip install cryptography
# RUN pip install -r requirements.txt 

# COPY . /ai/
# EXPOSE 8001
